[package]
name = "armoire"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parking_lot = "0.12.1"
rayon = "1.7.0"
itertools = "0.11.0"

[dev-dependencies]
checkito = "1.3"
